project_name: ai-fusion-gacode-simulation
simulation:
  tglf:
    command: >-
      [](make download file=<s3path>) bash src/run_container_simulation.sh tglf
    gpu_count: 0
    cpu_count: 6
    memory: 8  # 8GiB
    image: # gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/minimal
  cgyro:
    command: >-
      [](make download file=<s3path>) bash src/run_container_simulation.sh cgyro
    gpu_count: 3
    cpu_count: 6
    memory: 8  # 8GiB
    image: # gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/minimal
