project_name: ai-fusion-gacode-simulation
model:
  tglf:
    command: >-
      [](make download file=<s3path>;) bash src/run_simulation.sh tglf <s3path>
    gpu_count: 0
    cpu_count: 2
    ephemeral_storage: 1
    memory: 1
    image: gitlab-registry.nrp-nautilus.io/zclawrence/gacode-simulation:latest
  cgyro:
    command: >-
      [](make download file=<s3path>;) bash src/run_simulation.sh cgyro <s3path>
    gpu_count: 3
    cpu_count: 4
    ephemeral_storage: 1
    memory: 8
    image: gitlab-registry.nrp-nautilus.io/zclawrence/gacode-simulation:latest
