project_name: ai-fusion-gacode-simulation
model:
  tglf:
    command: >-
      [](. ./.venv/bin/activate; make download file=<s3path>;) bash src/run_simulation.sh tglf <s3path>
    gpu_count: 0
    cpu_count: 1
    ephemeral_storage: 1
    memory: 2
    image: gitlab-registry.nrp-nautilus.io/zclawrence/gacode-simulation:latest
  cgyro:
    command: >-
      [](. ./.venv/bin/activate; make download file=<s3path>;) bash src/run_simulation.sh cgyro <s3path>
    gpu_count: 0
    cpu_count: 32
    ephemeral_storage: 50
    memory: 8
    image: gitlab-registry.nrp-nautilus.io/wesleyliu728/gacode-simulation:latest
dataset:
  default:
    hparam:
      _s3path: ["cgyro-inputs-wesley/20250817_022804/batch-000/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-001/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-002/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-003/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-004/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-005/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-006/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-007/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-008/cgyro/","cgyro-inputs-wesley/20250817_022804/batch-009/cgyro/"]
run:
  model: [cgyro]
  dataset: [default]
