project_name: ai-fusion-gacode-simulation
model:
  tglf:
    command: >-
      [](. ./.venv/bin/activate; make download file=<s3path>;) bash src/run_simulation.sh tglf <s3path>
    gpu_count: 0
    cpu_count: 1
    ephemeral_storage: 1
    memory: 2
    image: gitlab-registry.nrp-nautilus.io/zclawrence/gacode-simulation:latest
  cgyro:
    command: >-
      [](. ./.venv/bin/activate; make download file=<s3path>;) bash src/run_simulation.sh cgyro <s3path>
    gpu_count: 2
    cpu_count: 16
    ephemeral_storage: 50
    memory: 8
    image: gitlab-registry.nrp-nautilus.io/zclawrence/gacode-simulation:latest
dataset:
  default:
    hparam:
      _s3path: ["cgyro-inputs-wesley/20250729_000014/batch-000/tglf/","cgyro-inputs-wesley/20250729_000014/batch-001/tglf/","cgyro-inputs-wesley/20250729_000014/batch-002/tglf/","cgyro-inputs-wesley/20250729_000014/batch-003/tglf/","cgyro-inputs-wesley/20250729_000014/batch-004/tglf/","cgyro-inputs-wesley/20250729_000014/batch-005/tglf/","cgyro-inputs-wesley/20250729_000014/batch-006/tglf/","cgyro-inputs-wesley/20250729_000014/batch-007/tglf/","cgyro-inputs-wesley/20250729_000014/batch-008/tglf/","cgyro-inputs-wesley/20250729_000014/batch-009/tglf/"]
run:
  model: [tglf]
  dataset: [default]
